version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db-network

volumes:
  db-data:
    driver: local

networks:
  db-network:
    driver: bridge
